/* TATNERA — aftercare v2, project-ID based */
(function(){
  'use strict';
  const Core=window.TatneraCore;let activeProjectId='',selectedPhoto='';const esc=Core.esc;
  const isoToday=()=>new Date().toISOString().slice(0,10);
  const addDays=(value,days)=>{const d=new Date((value||isoToday())+'T12:00:00');d.setDate(d.getDate()+days);return d.toISOString().slice(0,10);};
  const formatDate=value=>value?new Intl.DateTimeFormat('de-DE').format(new Date(value+'T12:00:00')):'—';
  const records=p=>Array.isArray(p?.aftercare?.records)?p.aftercare.records:[];

  function tattooDate(p){return Core.lastCompletedTattooDate(p.id)||p.aftercare?.tattooDate||'';}
  function followup(p){return p.aftercare?.followupDate||addDays(tattooDate(p)||isoToday(),42);}
  function status(p){const value=p.aftercare?.status||'Offen';return value==='Gute Heilung'?['good',value]:value==='Nachstechen empfohlen'?['warn',value]:value==='Nachstechen geplant'?['planned',value]:value==='Abgeschlossen'?['done',value]:['open','Offen'];}

  function install(){
    if(!document.querySelector('link[href="aftercare.css"]')){const link=document.createElement('link');link.rel='stylesheet';link.href='aftercare.css';document.head.appendChild(link);}
    buildDialog();let changed=false;(state.projects||[]).forEach(p=>{if(!p.aftercare){p.aftercare={status:'Offen',tattooDate:Core.lastCompletedTattooDate(p.id),followupDate:'',instructionsGiven:false,records:[]};changed=true;}else if(!Array.isArray(p.aftercare.records)){p.aftercare.records=[];changed=true;}});if(changed)persist();
    const detail=document.getElementById('projectDetail');if(detail)new MutationObserver(()=>queueMicrotask(inject)).observe(detail,{childList:true,subtree:true});document.addEventListener('tatnera:project-opened',inject);inject();
  }

  function buildDialog(){
    if(document.getElementById('aftercareDialog'))return;
    const dialog=document.createElement('dialog');dialog.id='aftercareDialog';dialog.className='dialog wide-dialog';dialog.innerHTML=`<form id="aftercareForm" style="padding:22px"><div class="dialog-head"><div><span class="eyebrow">Nachsorge</span><h2>Heilung dokumentieren</h2><p class="muted" id="aftercareDialogMeta"></p></div><button type="button" class="close-btn" data-close-aftercare>×</button></div><div class="form-grid three"><label>Kontrolldatum<input required type="date" name="date"></label><label>Heilungsstatus<select required name="status"><option>Gute Heilung</option><option>Beobachten</option><option>Nachstechen empfohlen</option><option>Nachstechen geplant</option><option>Abgeschlossen</option></select></label><label>Nächste Kontrolle<input type="date" name="nextCheck"></label><label class="full">Notiz<textarea name="note" rows="3"></textarea></label></div><div class="form-grid" style="margin-top:13px"><label>Foto vom Heilungsverlauf<input type="file" id="healingPhotoInput" accept="image/*"><span class="muted">Optional, lokal verkleinert gespeichert.</span></label><div class="healing-photo-preview" id="healingPhotoPreview">Kein Foto</div></div><label class="aftercare-toggle"><input type="checkbox" name="instructionsGiven"><span>Pflege-/Nachsorgehinweise wurden erklärt bzw. übergeben.</span></label><div class="aftercare-dialog-note">TATNERA dokumentiert den Verlauf und stellt keine medizinische Diagnose.</div><div class="dialog-actions"><button type="button" class="btn ghost" data-close-aftercare>Abbrechen</button><button type="submit" class="btn primary">Kontrolle speichern</button></div></form>`;document.body.appendChild(dialog);
    dialog.querySelectorAll('[data-close-aftercare]').forEach(btn=>btn.addEventListener('click',()=>dialog.close()));document.getElementById('aftercareForm').addEventListener('submit',saveRecord);document.getElementById('healingPhotoInput').addEventListener('change',handlePhoto);
  }

  function inject(){const id=Core.projectIdFromDetail(),p=Core.getProject(id),detail=document.getElementById('projectDetail');if(!id||!p||!detail)return;let card=detail.querySelector(`.aftercare-card[data-aftercare-project="${CSS.escape(id)}"]`);if(!card){card=document.createElement('section');card.className='aftercare-card';card.dataset.aftercareProject=id;const pane=detail.querySelector('[data-project-pane="aftercare"]');if(pane){pane.innerHTML='';pane.append(card);}else detail.append(card);}render(card,p);}

  function render(card,p){const [key,label]=status(p),date=tattooDate(p),next=followup(p),rows=[...records(p)].sort((a,b)=>(b.date||'').localeCompare(a.date||''));card.innerHTML=`<div class="aftercare-head"><div><span class="eyebrow">Nachsorge</span><h3>Heilung & Nachstechen</h3><p class="muted">Pflegehinweise, Heilungsverlauf und Nacharbeiten mit dieser Tattoo-Akte dokumentieren.</p></div><span class="aftercare-status ${key}">${esc(label)}</span></div><div class="aftercare-summary"><div><span>Letzter ausgeführter Tattoo-Termin</span><strong>${formatDate(date)}</strong><small>Zukünftige Sitzungen zählen hier nicht</small></div><div><span>Empfohlene Kontrolle</span><strong>${formatDate(next)}</strong><small>standardmäßig 6 Wochen später</small></div><div><span>Pflegehinweise</span><strong>${p.aftercare?.instructionsGiven?'Übergeben':'Offen'}</strong><small>${p.aftercare?.instructionsGiven?'dokumentiert':'noch bestätigen'}</small></div><div><span>Kontrollen</span><strong>${rows.length}</strong><small>im Heilungsverlauf</small></div></div><div class="aftercare-guide"><div class="aftercare-tip"><strong>Sauber halten</strong><span>Sanfte Reinigung nach Studioanweisung.</span></div><div class="aftercare-tip"><strong>Pflegen</strong><span>Empfohlene Pflege dünn anwenden.</span></div><div class="aftercare-tip"><strong>Schützen</strong><span>Reibung, Schwimmen, Sauna und intensive Sonne vermeiden.</span></div><div class="aftercare-tip"><strong>Nicht kratzen</strong><span>Schorf und Hautschüppchen nicht abziehen.</span></div></div><div class="aftercare-actions"><button class="btn primary" data-add-healing="${esc(p.id)}">+ Heilung dokumentieren</button><button class="btn ghost" data-plan-touchup="${esc(p.id)}">Nachstech-Termin planen</button><button class="btn ghost" data-toggle-instructions="${esc(p.id)}">${p.aftercare?.instructionsGiven?'Pflegehinweise ✓':'Pflegehinweise als übergeben markieren'}</button></div><div class="aftercare-history"><div class="aftercare-history-head"><h4>Heilungsverlauf</h4><span class="muted">${rows.length?`${rows.length} Einträge`:'Noch keine Kontrolle'}</span></div>${rows.length?rows.map(row=>`<div class="healing-entry"><div class="healing-date"><strong>${formatDate(row.date)}</strong><br><small>${esc(row.status)}</small></div><div>${row.photo?`<img class="healing-photo" src="${row.photo}" alt="Heilungsverlauf">`:''}<strong>${esc(row.note||'Keine Notiz')}</strong>${row.nextCheck?`<br><span>Nächste Kontrolle: ${formatDate(row.nextCheck)}</span>`:''}</div><button class="healing-delete" data-delete-healing="${esc(row.id)}">×</button></div>`).join(''):'<div class="aftercare-empty">Noch kein Heilungsverlauf dokumentiert.</div>'}</div>`;}

  function openDialog(id){activeProjectId=id;selectedPhoto='';const p=Core.getProject(id),form=document.getElementById('aftercareForm');if(!p||!form)return;form.reset();form.elements.date.value=isoToday();form.elements.status.value='Gute Heilung';form.elements.nextCheck.value=followup(p);form.elements.instructionsGiven.checked=Boolean(p.aftercare?.instructionsGiven);document.getElementById('aftercareDialogMeta').textContent=`${customerName(p.customerId)} · ${p.title}`;renderPhoto();document.getElementById('aftercareDialog').showModal();}
  function saveRecord(event){event.preventDefault();const p=Core.getProject(activeProjectId);if(!p)return;const d=Object.fromEntries(new FormData(event.currentTarget).entries());p.aftercare=p.aftercare||{records:[]};p.aftercare.records=p.aftercare.records||[];p.aftercare.records.push({id:'heal'+Date.now(),date:d.date,status:d.status,nextCheck:d.nextCheck||'',note:String(d.note||'').trim(),photo:selectedPhoto,createdAt:new Date().toISOString()});p.aftercare.status=d.status==='Beobachten'?'Offen':d.status;p.aftercare.followupDate=d.nextCheck||p.aftercare.followupDate||'';p.aftercare.tattooDate=Core.lastCompletedTattooDate(p.id)||p.aftercare.tattooDate||'';p.aftercare.instructionsGiven=event.currentTarget.elements.instructionsGiven.checked;persist();document.getElementById('aftercareDialog').close();inject();changed(p.id,'aftercare');}
  function changed(id,type){document.dispatchEvent(new CustomEvent('tatnera:data-changed',{detail:{type,projectId:id}}));}

  function planTouchup(id){const p=Core.getProject(id);if(!p||typeof openAppointmentDialog!=='function')return;const targetDate=p.aftercare?.followupDate||followup(p),before=new Set((state.calendarEvents||[]).map(item=>item.id));openAppointmentDialog('',targetDate);const form=document.getElementById('appointmentForm'),dialog=document.getElementById('appointmentDialog');if(!form||!dialog)return;Core.populateArtistSelect(form.elements.artist,p.artist);form.elements.customerId.value=p.customerId;form.elements.projectId.value=p.id;form.elements.type.value='touchup';form.elements.status.value='Angefragt';form.elements.duration.value=60;form.elements.notes.value='Nachstechen / Heilungskontrolle';const onSubmit=()=>setTimeout(()=>{const saved=(state.calendarEvents||[]).find(item=>!before.has(item.id)&&item.projectId===p.id&&item.type==='touchup');if(!saved)return;p.aftercare.status='Nachstechen geplant';p.aftercare.followupDate=saved.date;persist();inject();changed(p.id,'aftercare');},0);form.addEventListener('submit',onSubmit,{once:true});}

  async function handlePhoto(event){const file=event.target.files?.[0];if(!file)return;try{selectedPhoto=await compress(file);renderPhoto();}catch(_error){alert('Das Bild konnte nicht verarbeitet werden.');}}
  function renderPhoto(){const root=document.getElementById('healingPhotoPreview');if(root)root.innerHTML=selectedPhoto?`<img src="${selectedPhoto}" alt="Vorschau">`:'Kein Foto';}
  function compress(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.75));};img.src=reader.result;};reader.readAsDataURL(file);});}

  document.addEventListener('click',event=>{const add=event.target.closest('[data-add-healing]');if(add){event.preventDefault();openDialog(add.dataset.addHealing);return;}const plan=event.target.closest('[data-plan-touchup]');if(plan){event.preventDefault();planTouchup(plan.dataset.planTouchup);return;}const toggle=event.target.closest('[data-toggle-instructions]');if(toggle){event.preventDefault();const p=Core.getProject(toggle.dataset.toggleInstructions);if(p){p.aftercare.instructionsGiven=!p.aftercare.instructionsGiven;persist();inject();changed(p.id,'aftercare');}return;}const del=event.target.closest('[data-delete-healing]');if(del){event.preventDefault();const p=Core.currentProject();if(!p||!confirm('Diesen Nachsorge-Eintrag wirklich löschen?'))return;p.aftercare.records=records(p).filter(item=>item.id!==del.dataset.deleteHealing);const latest=[...p.aftercare.records].sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0];const planned=(state.calendarEvents||[]).find(item=>item.projectId===p.id&&item.type==='touchup'&&item.date>=isoToday());p.aftercare.status=planned?'Nachstechen geplant':latest?(latest.status==='Beobachten'?'Offen':latest.status):'Offen';p.aftercare.followupDate=latest?.nextCheck||planned?.date||'';persist();inject();changed(p.id,'aftercare');}});
  install();
})();
