/* TATNERA — Ink Passport v2, project-ID based */
(function(){
  'use strict';
  const Core=window.TatneraCore;const esc=Core.esc;let activeInkId='',activeProjectId='',selectedPhoto='';
  const seedInks=[
    {id:'ink1',manufacturer:'Dynamic',name:'Black',code:'BLK',batch:'DB-2608',purchaseDate:'2026-08-12',expiryDate:'2027-05-31',notes:'Standard Black',photo:''},
    {id:'ink2',manufacturer:'Panthera',name:'Grey',code:'GREY',batch:'PG-0726',purchaseDate:'2026-07-20',expiryDate:'2026-10-10',notes:'Für Greywash / Schattierung',photo:''},
    {id:'ink3',manufacturer:'Panthera',name:'Black',code:'BLACK',batch:'PB-1125',purchaseDate:'2026-01-18',expiryDate:'2027-01-31',notes:'',photo:''},
    {id:'ink4',manufacturer:'Demo Ink',name:'Red',code:'RED01',batch:'DR-0124',purchaseDate:'2025-01-10',expiryDate:'2026-08-15',notes:'Demo einer abgelaufenen Charge',photo:''}
  ];
  state.inks=JSON.parse(localStorage.getItem('tatnera_inks')||'null')||seedInks;
  const formatDate=value=>value?new Intl.DateTimeFormat('de-DE').format(new Date(value+'T12:00:00')):'—';
  const daysUntil=value=>{if(!value)return Infinity;const now=new Date();now.setHours(0,0,0,0);const date=new Date(value+'T23:59:59');return Math.ceil((date-now)/86400000);};
  const inkStatus=ink=>{const days=daysUntil(ink.expiryDate);return days<0?{key:'expired',label:'Abgelaufen',days}:days<=60?{key:'soon',label:`Läuft in ${days} Tagen ab`,days}:{key:'active',label:'Aktiv',days};};
  const inkById=id=>(state.inks||[]).find(item=>item.id===id)||null;
  const usageFor=id=>(state.projects||[]).filter(project=>(project.inkIds||[]).includes(id));
  function persistAll(){localStorage.setItem('tatnera_inks',JSON.stringify(state.inks));persist();document.dispatchEvent(new CustomEvent('tatnera:data-changed',{detail:{type:'ink'}}));}

  function install(){
    if(!document.querySelector('link[href="ink.css"]')){const link=document.createElement('link');link.rel='stylesheet';link.href='ink.css';document.head.appendChild(link);}
    buildSettings();buildDialogs();migrate();renderSettings();
    const detail=document.getElementById('projectDetail');if(detail)new MutationObserver(()=>queueMicrotask(injectProject)).observe(detail,{childList:true,subtree:true});document.addEventListener('tatnera:project-opened',injectProject);injectProject();
  }

  function migrate(){let changed=false;(state.projects||[]).forEach(p=>{if(!Array.isArray(p.inkIds)){p.inkIds=[];changed=true;}(p.colors||[]).forEach(label=>{const match=String(label).match(/Charge\s+(.+)$/i);if(!match)return;const ink=(state.inks||[]).find(item=>item.batch===match[1].trim());if(ink&&!p.inkIds.includes(ink.id)){p.inkIds.push(ink.id);changed=true;}});});if(changed)persistAll();}

  function buildSettings(){const settings=document.getElementById('settings');if(!settings)return;settings.querySelector('.ink-settings')?.remove();const section=document.createElement('div');section.className='ink-settings';section.innerHTML=`<div class="ink-head"><div><span class="eyebrow">Studioverwaltung</span><h2>Farben & Chargen</h2><p class="muted">Jede Flasche bzw. Charge einmal erfassen und anschließend den Tattoo-Akten zuordnen.</p></div><button class="btn primary" id="addInkBtn">+ Farbe / Charge</button></div><div class="ink-stats" id="inkStats"></div><div class="ink-table-wrap"><table class="ink-table"><thead><tr><th>Farbe</th><th>Charge</th><th>Gekauft</th><th>Ablauf</th><th>Status</th><th>Verwendet</th><th></th></tr></thead><tbody id="inkTableBody"></tbody></table></div>`;settings.appendChild(section);document.getElementById('addInkBtn').addEventListener('click',()=>openInk());}

  function buildDialogs(){
    if(document.getElementById('inkDialog'))return;
    const dialog=document.createElement('dialog');dialog.id='inkDialog';dialog.className='dialog ink-dialog';dialog.innerHTML=`<form id="inkForm"><div class="dialog-head"><div><span class="eyebrow">Ink Passport</span><h2 id="inkDialogTitle">Farbe / Charge anlegen</h2></div><button type="button" class="close-btn" data-close-ink>×</button></div><div class="form-grid three"><label>Hersteller<input required name="manufacturer"></label><label>Farbname<input required name="name"></label><label>Farb-/Produktcode<input name="code"></label><label>Charge / Lot<input required name="batch"></label><label>Kaufdatum<input type="date" name="purchaseDate"></label><label>Ablaufdatum<input type="date" name="expiryDate"></label><label class="full">Notizen<textarea name="notes" rows="2"></textarea></label></div><div class="ink-photo-row" style="margin-top:14px"><label>Foto vom Etikett<input type="file" id="inkPhotoInput" accept="image/*"><span class="muted">Optional, lokal verkleinert gespeichert.</span></label><div class="ink-photo-preview" id="inkPhotoPreview">Kein Foto</div></div><div class="ink-dialog-note">Eine Charge ist ein eigener Datensatz und bleibt für die Rückverfolgung eindeutig.</div><div class="ink-dialog-tools"><button type="button" class="ink-delete" id="deleteInkBtn" hidden>Charge entfernen</button><div class="dialog-actions"><button type="button" class="btn ghost" data-close-ink>Abbrechen</button><button type="submit" class="btn primary">Speichern</button></div></div></form>`;document.body.appendChild(dialog);
    const picker=document.createElement('dialog');picker.id='inkPickerDialog';picker.className='dialog ink-dialog';picker.innerHTML=`<form id="inkPickerForm"><div class="dialog-head"><div><span class="eyebrow">Tattoo-Akte</span><h2>Verwendete Farben auswählen</h2><p class="muted" id="inkPickerMeta"></p></div><button type="button" class="close-btn" data-close-picker>×</button></div><div class="ink-picker-list" id="inkPickerList"></div><div class="dialog-actions"><button type="button" class="btn ghost" data-close-picker>Abbrechen</button><button type="submit" class="btn primary">Auswahl speichern</button></div></form>`;document.body.appendChild(picker);
    const usage=document.createElement('dialog');usage.id='inkUsageDialog';usage.className='dialog';usage.innerHTML=`<div style="padding:22px"><div class="dialog-head"><div><span class="eyebrow">Rückverfolgung</span><h2 id="inkUsageTitle">Verwendung</h2></div><button type="button" class="close-btn" data-close-usage>×</button></div><div id="inkUsageBody"></div><div class="dialog-actions"><button type="button" class="btn ghost" data-close-usage>Schließen</button></div></div>`;document.body.appendChild(usage);
    document.querySelectorAll('[data-close-ink]').forEach(btn=>btn.addEventListener('click',()=>dialog.close()));document.querySelectorAll('[data-close-picker]').forEach(btn=>btn.addEventListener('click',()=>picker.close()));document.querySelectorAll('[data-close-usage]').forEach(btn=>btn.addEventListener('click',()=>usage.close()));
    document.getElementById('inkForm').addEventListener('submit',saveInk);document.getElementById('inkPickerForm').addEventListener('submit',saveProjectInks);document.getElementById('inkPhotoInput').addEventListener('change',handlePhoto);document.getElementById('deleteInkBtn').addEventListener('click',deleteInk);
  }

  function renderSettings(){const stats=document.getElementById('inkStats'),body=document.getElementById('inkTableBody');if(!stats||!body)return;const statuses=state.inks.map(inkStatus),active=statuses.filter(s=>s.key==='active').length,soon=statuses.filter(s=>s.key==='soon').length,expired=statuses.filter(s=>s.key==='expired').length;stats.innerHTML=`<div class="ink-stat"><span>Chargen gesamt</span><strong>${state.inks.length}</strong><small>im Studio erfasst</small></div><div class="ink-stat"><span>Aktiv</span><strong>${active}</strong><small>ohne aktuelle Warnung</small></div><div class="ink-stat warn"><span>Läuft bald ab</span><strong>${soon}</strong><small>innerhalb 60 Tagen</small></div><div class="ink-stat danger"><span>Abgelaufen</span><strong>${expired}</strong><small>nicht neu verwenden</small></div>`;body.innerHTML=state.inks.map(ink=>{const st=inkStatus(ink),used=usageFor(ink.id).length;return `<tr><td><div class="ink-name-cell"><div class="ink-swatch">${ink.photo?`<img src="${ink.photo}" alt="Etikett">`:'INK'}</div><div><strong>${esc(ink.name)}</strong><small>${esc(ink.manufacturer)}${ink.code?' · '+esc(ink.code):''}</small></div></div></td><td><strong>${esc(ink.batch)}</strong></td><td>${formatDate(ink.purchaseDate)}</td><td>${formatDate(ink.expiryDate)}</td><td><span class="ink-status ${st.key}">${esc(st.label)}</span></td><td><button class="ink-action" data-usage-id="${esc(ink.id)}">${used} Tattoo${used===1?'':'s'} →</button></td><td><button class="ink-action" data-edit-ink="${esc(ink.id)}">Bearbeiten</button></td></tr>`;}).join('')||'<tr><td colspan="7"><div class="ink-empty">Noch keine Farben oder Chargen erfasst.</div></td></tr>';}

  function injectProject(){const id=Core.projectIdFromDetail(),p=Core.getProject(id),detail=document.getElementById('projectDetail');if(!id||!p||!detail)return;let panel=detail.querySelector(`.ink-project-panel[data-ink-project="${CSS.escape(id)}"]`);if(!panel){panel=document.createElement('section');panel.className='detail-card ink-project-panel';panel.dataset.inkProject=id;const pane=detail.querySelector('[data-project-pane="documents"]');if(pane)pane.append(panel);else detail.append(panel);}panel.innerHTML=projectHtml(p);}
  function projectHtml(p){const inks=(p.inkIds||[]).map(inkById).filter(Boolean);return `<span class="eyebrow">Ink Passport</span><h3>Farben & Chargen</h3><p class="muted">Konkrete Chargen für dieses Tattoo dokumentieren und rückverfolgen.</p>${inks.length?`<div class="ink-project-list">${inks.map(ink=>{const st=inkStatus(ink);return `<div class="ink-project-item"><div><strong>${esc(ink.manufacturer)} · ${esc(ink.name)}</strong><small>Charge ${esc(ink.batch)}${ink.code?' · '+esc(ink.code):''}</small>${st.key!=='active'?`<div class="ink-warning-line">⚠ ${esc(st.label)}</div>`:''}</div><div class="right"><span class="ink-status ${st.key}">${st.key==='active'?'Dokumentiert':esc(st.label)}</span><button class="ink-action" data-usage-id="${esc(ink.id)}">Rückverfolgung →</button></div></div>`;}).join('')}</div>`:'<div class="ink-empty">Noch keine Charge zugeordnet.</div>'}<button class="btn primary" style="margin-top:12px" data-pick-project-inks="${esc(p.id)}">Farben / Chargen auswählen</button>`;}

  function openInk(id=''){activeInkId=id;const ink=inkById(id),form=document.getElementById('inkForm');form.reset();selectedPhoto=ink?.photo||'';form.elements.manufacturer.value=ink?.manufacturer||'';form.elements.name.value=ink?.name||'';form.elements.code.value=ink?.code||'';form.elements.batch.value=ink?.batch||'';form.elements.purchaseDate.value=ink?.purchaseDate||'';form.elements.expiryDate.value=ink?.expiryDate||'';form.elements.notes.value=ink?.notes||'';document.getElementById('inkDialogTitle').textContent=ink?'Farbe / Charge bearbeiten':'Farbe / Charge anlegen';const del=document.getElementById('deleteInkBtn'),uses=ink?usageFor(ink.id).length:0;del.hidden=!ink;del.disabled=uses>0;del.textContent=uses?`In ${uses} Tattoo(s) verwendet`:'Charge entfernen';renderPhoto();document.getElementById('inkDialog').showModal();}
  function saveInk(event){event.preventDefault();const d=Object.fromEntries(new FormData(event.currentTarget).entries()),old=inkById(activeInkId),payload={id:activeInkId||'ink'+Date.now(),manufacturer:d.manufacturer.trim(),name:d.name.trim(),code:d.code.trim(),batch:d.batch.trim(),purchaseDate:d.purchaseDate,expiryDate:d.expiryDate,notes:d.notes.trim(),photo:selectedPhoto};if(old&&usageFor(old.id).length&&old.batch.toLowerCase()!==payload.batch.toLowerCase()){alert('Eine bereits verwendete Chargennummer kann nicht geändert werden. Lege eine neue Charge an.');return;}const duplicate=state.inks.find(item=>item.batch.toLowerCase()===payload.batch.toLowerCase()&&item.id!==payload.id);if(duplicate&&!confirm(`Die Charge ${payload.batch} existiert bereits. Trotzdem speichern?`))return;const index=state.inks.findIndex(item=>item.id===payload.id);if(index>=0)state.inks[index]=payload;else state.inks.unshift(payload);persistAll();renderSettings();injectProject();document.getElementById('inkDialog').close();}
  function deleteInk(){const ink=inkById(activeInkId);if(!ink)return;if(usageFor(ink.id).length){alert('Diese Charge ist bereits Tattoo-Akten zugeordnet und kann nicht entfernt werden.');return;}if(!confirm(`Charge ${ink.batch} wirklich entfernen?`))return;state.inks=state.inks.filter(item=>item.id!==ink.id);persistAll();renderSettings();document.getElementById('inkDialog').close();}

  function openPicker(id){activeProjectId=id;const p=Core.getProject(id);if(!p)return;document.getElementById('inkPickerMeta').textContent=`${customerName(p.customerId)} · ${p.title}`;document.getElementById('inkPickerList').innerHTML=state.inks.map(ink=>{const st=inkStatus(ink),checked=(p.inkIds||[]).includes(ink.id),disabled=st.key==='expired'&&!checked;return `<label class="ink-picker-item ${st.key}"><input type="checkbox" name="inkId" value="${esc(ink.id)}" ${checked?'checked':''} ${disabled?'disabled':''}><div><strong>${esc(ink.manufacturer)} · ${esc(ink.name)}</strong><span>Charge ${esc(ink.batch)} · ${formatDate(ink.expiryDate)}</span></div><span class="ink-status ${st.key}">${esc(st.label)}</span></label>`;}).join('');document.getElementById('inkPickerDialog').showModal();}
  function saveProjectInks(event){event.preventDefault();const p=Core.getProject(activeProjectId);if(!p)return;p.inkIds=[...new FormData(event.currentTarget).getAll('inkId')];persist();document.getElementById('inkPickerDialog').close();injectProject();renderSettings();document.dispatchEvent(new CustomEvent('tatnera:data-changed',{detail:{type:'ink',projectId:p.id}}));}
  function openUsage(id){const ink=inkById(id),uses=usageFor(id);if(!ink)return;document.getElementById('inkUsageTitle').textContent=`${ink.manufacturer} · ${ink.name} · ${ink.batch}`;document.getElementById('inkUsageBody').innerHTML=uses.length?`<div class="ink-usage-list">${uses.map(p=>`<button data-open-ink-project="${esc(p.id)}"><div><strong>${esc(p.title)}</strong><span>${esc(customerName(p.customerId))} · ${esc(p.placement||'—')}</span></div><span>→</span></button>`).join('')}</div>`:'<div class="ink-empty">Diese Charge wurde noch keinem Tattoo zugeordnet.</div>';document.getElementById('inkUsageDialog').showModal();}

  async function handlePhoto(event){const file=event.target.files?.[0];if(!file)return;try{selectedPhoto=await compress(file);renderPhoto();}catch(_error){alert('Das Bild konnte nicht verarbeitet werden.');}}
  function renderPhoto(){const root=document.getElementById('inkPhotoPreview');if(root)root.innerHTML=selectedPhoto?`<img src="${selectedPhoto}" alt="Etikettvorschau">`:'Kein Foto';}
  function compress(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=640,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.72));};img.src=reader.result;};reader.readAsDataURL(file);});}

  document.addEventListener('click',event=>{const edit=event.target.closest('[data-edit-ink]');if(edit){event.preventDefault();openInk(edit.dataset.editInk);return;}const usage=event.target.closest('[data-usage-id]');if(usage){event.preventDefault();openUsage(usage.dataset.usageId);return;}const pick=event.target.closest('[data-pick-project-inks]');if(pick){event.preventDefault();openPicker(pick.dataset.pickProjectInks);return;}const open=event.target.closest('[data-open-ink-project]');if(open){event.preventDefault();document.getElementById('inkUsageDialog').close();openProject(open.dataset.openInkProject);setTimeout(()=>Core.activateProjectTab('documents'),0);}});
  install();
})();
