/* TATNERA — studio trial status & Stripe billing UI */
(function(){
  'use strict';
  const DAY=86400000,MIN_RECHECK_MS=60000;
  const STRIPE_PAYMENT_LINK='https://buy.stripe.com/test_28EbJ3dwv9G0fRd6mNes000';
  let running=false,lastCheck=0;
  function installStyles(){if(document.getElementById('tatneraSubscriptionStyles'))return;const s=document.createElement('style');s.id='tatneraSubscriptionStyles';s.textContent=`
.tatnera-trial-badge{display:inline-flex;align-items:center;gap:7px;border-radius:999px;padding:8px 10px;font-size:11px;font-weight:850;white-space:nowrap}
.tatnera-trial-badge:before{content:'';width:7px;height:7px;border-radius:50%}
.tatnera-subscription-overlay{position:fixed;inset:0;z-index:100000;display:grid;place-items:center;padding:22px;backdrop-filter:blur(14px)}
.tatnera-subscription-card{width:min(590px,100%);border-radius:24px;padding:30px;box-shadow:0 34px 110px rgba(0,0,0,.35)}
.tatnera-subscription-mark{width:48px;height:48px;border-radius:14px;display:grid;place-items:center;font-size:23px;font-weight:950;margin-bottom:22px}
.tatnera-subscription-card .eyebrow{font-size:10px;font-weight:850;text-transform:uppercase;letter-spacing:.13em}
.tatnera-subscription-card h1{font-size:32px;line-height:1.08;margin:8px 0 12px}.tatnera-subscription-card p{line-height:1.65;margin:0}
.tatnera-subscription-info{margin:20px 0;border-radius:14px;padding:15px;font-size:13px;line-height:1.55}
.tatnera-subscription-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px}.tatnera-subscription-actions a,.tatnera-subscription-actions button{border-radius:11px;padding:12px 15px;font:inherit;font-weight:850;cursor:pointer;text-decoration:none}
.tatnera-billing-success{position:fixed;right:18px;top:18px;z-index:100001;width:min(430px,calc(100% - 36px));border-radius:16px;padding:16px 18px;box-shadow:0 20px 60px rgba(0,0,0,.25)}.tatnera-billing-success strong{display:block;margin-bottom:5px}.tatnera-billing-success span{font-size:13px;line-height:1.45}
:root[data-theme="dark"] .tatnera-subscription-overlay{background:rgba(12,13,14,.94)}:root[data-theme="dark"] .tatnera-subscription-card{background:#171512;color:#f6f3ef;border:1px solid #4d3928}:root[data-theme="dark"] .tatnera-subscription-mark{background:#c79a5b;color:#17110a}:root[data-theme="dark"] .tatnera-subscription-card .eyebrow{color:#cfa66d}:root[data-theme="dark"] .tatnera-subscription-card p{color:#b8afa4}:root[data-theme="dark"] .tatnera-subscription-info{border:1px solid #4d3928;background:#11100e;color:#cfc5b8}:root[data-theme="dark"] .tatnera-subscription-info strong{color:#f3eee7}:root[data-theme="dark"] .tatnera-subscription-actions .primary{border:1px solid #d0a25f;background:linear-gradient(135deg,#d1a565,#b77f45);color:#17110a}:root[data-theme="dark"] .tatnera-subscription-actions .secondary{background:#211c16;color:#f1ebe4;border:1px solid #4f3b28}
:root[data-theme="light"] .tatnera-subscription-overlay{background:rgba(244,246,244,.94)}:root[data-theme="light"] .tatnera-subscription-card{background:#fff;color:#1f2621;border:1px solid #d7ddd8}:root[data-theme="light"] .tatnera-subscription-mark{background:#232a24;color:#fff}:root[data-theme="light"] .tatnera-subscription-card .eyebrow{color:#465349}:root[data-theme="light"] .tatnera-subscription-card p{color:#667069}:root[data-theme="light"] .tatnera-subscription-info{border:1px solid #d7ddd8;background:#f4f6f4;color:#505a53}:root[data-theme="light"] .tatnera-subscription-info strong{color:#202722}:root[data-theme="light"] .tatnera-subscription-actions .primary{border:1px solid #232a24;background:#232a24;color:#fff}:root[data-theme="light"] .tatnera-subscription-actions .secondary{background:#fff;color:#232a24;border:1px solid #cbd2cc}
:root[data-theme="pink"] .tatnera-subscription-overlay{background:rgba(15,9,13,.94)}:root[data-theme="pink"] .tatnera-subscription-card{background:#181116;color:#fff5fa;border:1px solid #51283d}:root[data-theme="pink"] .tatnera-subscription-mark{background:#ff4fa3;color:#160710}:root[data-theme="pink"] .tatnera-subscription-card .eyebrow{color:#ff79b9}:root[data-theme="pink"] .tatnera-subscription-card p{color:#c9b2be}:root[data-theme="pink"] .tatnera-subscription-info{border:1px solid #51283d;background:#120c10;color:#d8c1cc}:root[data-theme="pink"] .tatnera-subscription-info strong{color:#fff2f8}:root[data-theme="pink"] .tatnera-subscription-actions .primary{border:1px solid #ff4fa3;background:#ff4fa3;color:#160710}:root[data-theme="pink"] .tatnera-subscription-actions .secondary{background:#24131c;color:#fff1f8;border:1px solid #5b2a43}
:root[data-theme="dark"] .tatnera-billing-success{border:1px solid #4d3928;background:#171512;color:#f3eee7}:root[data-theme="dark"] .tatnera-billing-success strong{color:#d1a565}:root[data-theme="light"] .tatnera-billing-success{border:1px solid #ccd2cc;background:#fff;color:#232a24}:root[data-theme="light"] .tatnera-billing-success strong{color:#39463c}:root[data-theme="pink"] .tatnera-billing-success{border:1px solid #5b2a43;background:#181116;color:#fff1f8}:root[data-theme="pink"] .tatnera-billing-success strong{color:#ff79b9}
@media(max-width:760px){.tatnera-trial-badge{font-size:9px;padding:7px 8px}.tatnera-subscription-card{padding:24px}.tatnera-subscription-card h1{font-size:27px}}
`;document.head.appendChild(s)}
  function formatDate(v){try{return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v))}catch(_){return''}}
  function checkoutUrl(id){const u=new URL(STRIPE_PAYMENT_LINK);if(id)u.searchParams.set('client_reference_id',id);try{const e=window.TatneraAuth?.user?.()?.email||window.TatneraAuth?.currentUser?.()?.email||'';if(e)u.searchParams.set('prefilled_email',e)}catch(_){}return u.toString()}
  function showBadge(end){const a=document.querySelector('.top-actions');if(!a)return;let b=document.getElementById('tatneraTrialBadge');if(!b){b=document.createElement('span');b.id='tatneraTrialBadge';b.className='tatnera-trial-badge';a.prepend(b)}const d=Math.max(1,Math.ceil(Math.max(0,new Date(end)-Date.now())/DAY));b.textContent=d===1?'Test · letzter Tag':`Test · ${d} Tage`;b.title=`Kostenlose Testphase bis ${formatDate(end)} · keine automatische Verlängerung`}
  function hideBadge(){document.getElementById('tatneraTrialBadge')?.remove()}
  function showLock(status,end,id){const old=document.getElementById('tatneraSubscriptionOverlay');if(old){const c=old.querySelector('[data-stripe-checkout]');if(c)c.href=checkoutUrl(id);return}hideBadge();const expired=status==='trial',o=document.createElement('div');o.id='tatneraSubscriptionOverlay';o.className='tatnera-subscription-overlay';o.innerHTML=`<section class="tatnera-subscription-card" role="dialog" aria-modal="true"><div class="tatnera-subscription-mark">T</div><span class="eyebrow">TATNERA Studio Software</span><h1>${expired?'Deine Testphase ist beendet.':'Dein Studio-Zugang ist derzeit nicht aktiv.'}</h1><p>${expired?'Die 14 Tage sind abgelaufen. Es wurde nichts automatisch verlängert und es entstehen keine Kosten.':'Der aktuelle Studio-Status erlaubt im Moment keinen Zugriff auf das Dashboard.'}</p><div class="tatnera-subscription-info">${expired?`Testzeit beendet am <strong>${formatDate(end)}</strong>.<br>Deine Studio-Daten bleiben bestehen.`:'Deine Studio-Daten bleiben bestehen. Sobald der Zugang wieder aktiviert ist, kannst du an derselben Stelle weiterarbeiten.'}<br><br><strong>19 € pro Monat</strong> · monatliches TATNERA Studio-Abo.</div><div class="tatnera-subscription-actions"><a class="primary" data-stripe-checkout href="${checkoutUrl(id)}">Für 19 € / Monat freischalten</a><button class="secondary" type="button" data-trial-logout>Abmelden</button></div></section>`;o.querySelector('[data-trial-logout]')?.addEventListener('click',()=>window.TatneraAuth?.logout?.());document.body.appendChild(o)}
  function showBillingSuccess(){if(document.getElementById('tatneraBillingSuccess'))return;installStyles();const n=document.createElement('div');n.id='tatneraBillingSuccess';n.className='tatnera-billing-success';n.innerHTML='<strong>Zahlung abgeschlossen.</strong><span>Stripe bestätigt dein Abo. TATNERA aktualisiert den Studio-Zugang automatisch.</span>';document.body.appendChild(n);setTimeout(()=>n.remove(),9000)}
  async function checkSubscription(force=false){if(running)return;const a=window.TatneraAuth,id=a?.studioId?.(),c=a?.client;if(!id||!c)return;const now=Date.now();if(!force&&now-lastCheck<MIN_RECHECK_MS)return;running=true;lastCheck=now;try{installStyles();const{data,error}=await c.from('studios').select('subscription_status,trial_started_at,trial_ends_at,stripe_subscription_id,stripe_cancel_at_period_end').eq('id',id).single();if(error)throw error;const st=String(data?.subscription_status||'trial'),end=data?.trial_ends_at,expired=st==='trial'&&end&&new Date(end)<=new Date();if(st==='active'){hideBadge();document.getElementById('tatneraSubscriptionOverlay')?.remove();return}if(st==='trial'&&!expired){showBadge(end);document.getElementById('tatneraSubscriptionOverlay')?.remove();return}if(expired||st==='paused'||st==='cancelled')showLock(st,end,id)}catch(e){console.warn('TATNERA subscription status could not be loaded.',e)}finally{running=false}}
  function handleStripeReturn(){let ok=false;try{ok=new URLSearchParams(location.search).get('billing')==='success'}catch(_){}if(!ok)return;showBillingSuccess();[0,1200,3000,6000,10000].forEach(d=>setTimeout(()=>checkSubscription(true),d));try{const u=new URL(location.href);u.searchParams.delete('billing');u.searchParams.delete('session_id');history.replaceState(history.state,'',u.pathname+u.search+u.hash)}catch(_){}}
  document.addEventListener('tatnera:auth-ready',()=>{checkSubscription(true);handleStripeReturn()});window.addEventListener('focus',()=>checkSubscription(false));setTimeout(()=>{checkSubscription(true);handleStripeReturn()},700)
})();